import {
  Offer,
  OfferCompanyType,
  OfferLocation,
  OfferPriority,
  OfferSalaryCurrency,
  OfferStatus,
} from '@jhh/shared/domain';

type DefaultOffer = Omit<Offer, 'userId' | 'createdAt' | 'updatedAt' | 'id'>;

const defaultDescription: string =
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n" +
  '\n' +
  '- lorem ipsum\n' +
  '- lorem ipsum\n' +
  '- lorem ipsum\n' +
  '- lorem ipsum';

function subtractDays(date: Date, days: number): Date {
  const result: Date = new Date(date);
  result.setDate(result.getDate() - days);
  return result;
}

const today: Date = new Date();

const defaultOffers: DefaultOffer[] = [
  {
    statusUpdates: [
      { date: subtractDays(today, 30), status: OfferStatus.Applied },
      { date: subtractDays(today, 20), status: OfferStatus.Interviewing },
      { date: subtractDays(today, 10), status: OfferStatus.Rejected },
    ],
    position: 'Frontend Developer',
    slug: 'frontend-developer',
    link: 'http://example.com/frontend',
    company: 'Tech Solutions',
    companyType: OfferCompanyType.SoftwareHouse,
    location: OfferLocation.Remote,
    status: OfferStatus.Rejected,
    priority: OfferPriority.High,
    minSalary: 9000,
    maxSalary: 16000,
    salaryCurrency: OfferSalaryCurrency.PLN,
    email: 'hr@example.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 10), status: OfferStatus.Applied },
      { date: subtractDays(today, 3), status: OfferStatus.Interviewing },
    ],
    position: 'Backend Developer',
    slug: 'backend-developer',
    link: 'http://example.com/backend',
    company: 'Innovatech',
    companyType: OfferCompanyType.SoftwareHouse,
    location: OfferLocation.OnSite,
    status: OfferStatus.Interviewing,
    priority: OfferPriority.Medium,
    minSalary: 3600,
    maxSalary: null,
    salaryCurrency: OfferSalaryCurrency.EUR,
    email: 'careers@example.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [],
    position: 'Full Stack Developer',
    slug: 'full-stack-developer',
    link: 'http://example.com/fullstack',
    company: 'CodeCraft',
    companyType: OfferCompanyType.Other,
    location: OfferLocation.Hybrid,
    status: OfferStatus.NotApplied,
    priority: OfferPriority.Low,
    minSalary: 3550,
    maxSalary: 5800,
    salaryCurrency: OfferSalaryCurrency.GBP,
    email: null,
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 30), status: OfferStatus.Applied },
      { date: subtractDays(today, 20), status: OfferStatus.Interviewing },
      { date: subtractDays(today, 10), status: OfferStatus.Rejected },
    ],
    position: 'DevOps Engineer',
    slug: 'devops-engineer',
    link: 'http://example.com/devops',
    company: 'CloudNet',
    companyType: OfferCompanyType.Product,
    location: OfferLocation.Hybrid,
    status: OfferStatus.Rejected,
    priority: OfferPriority.Medium,
    minSalary: null,
    maxSalary: 6000,
    salaryCurrency: OfferSalaryCurrency.EUR,
    email: 'recruit@example.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 40), status: OfferStatus.Applied },
      { date: subtractDays(today, 25), status: OfferStatus.Interviewing },
      { date: subtractDays(today, 15), status: OfferStatus.OfferReceived },
    ],
    position: 'UI/UX Designer',
    slug: 'ui-ux-designer',
    link: 'http://example.com/uiux',
    company: 'DesignHub',
    companyType: OfferCompanyType.Outsourcing,
    location: OfferLocation.OnSite,
    status: OfferStatus.OfferReceived,
    priority: OfferPriority.Low,
    minSalary: null,
    maxSalary: null,
    salaryCurrency: null,
    email: 'talent@example.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 50), status: OfferStatus.Applied },
      { date: subtractDays(today, 35), status: OfferStatus.Interviewing },
      { date: subtractDays(today, 20), status: OfferStatus.OfferReceived },
      { date: subtractDays(today, 5), status: OfferStatus.Accepted },
    ],
    position: 'Software Architect',
    slug: 'software-architect',
    link: 'http://example.com/architect',
    company: 'BuildTech',
    companyType: OfferCompanyType.Enterprise,
    location: OfferLocation.Remote,
    status: OfferStatus.Accepted,
    priority: OfferPriority.High,
    minSalary: 5800,
    maxSalary: 7000,
    salaryCurrency: OfferSalaryCurrency.USD,
    email: 'careers@example.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 2), status: OfferStatus.Applied },
    ],
    position: 'Mobile Developer',
    slug: 'mobile-developer',
    link: 'http://example.com/mobile',
    company: 'Mobile Innovations',
    companyType: OfferCompanyType.Product,
    location: OfferLocation.Remote,
    status: OfferStatus.Applied,
    priority: OfferPriority.Medium,
    minSalary: 2500,
    maxSalary: 6000,
    salaryCurrency: OfferSalaryCurrency.USD,
    email: 'jobs@mobileinnovations.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 7), status: OfferStatus.Applied },
    ],
    position: 'QA Engineer',
    slug: 'qa-engineer',
    link: 'http://example.com/qa',
    company: 'Quality Assurance Ltd.',
    companyType: OfferCompanyType.SoftwareHouse,
    location: OfferLocation.OnSite,
    status: OfferStatus.Applied,
    priority: OfferPriority.High,
    minSalary: 3000,
    maxSalary: 5150,
    salaryCurrency: OfferSalaryCurrency.PLN,
    email: 'hr@qaltd.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [],
    position: 'Data Scientist',
    slug: 'data-scientist',
    link: 'http://example.com/data-scientist',
    company: 'DataWise',
    companyType: OfferCompanyType.Enterprise,
    location: OfferLocation.Hybrid,
    status: OfferStatus.NotApplied,
    priority: OfferPriority.Low,
    minSalary: 9500,
    maxSalary: 12000,
    salaryCurrency: OfferSalaryCurrency.GBP,
    email: 'contact@datawise.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 1), status: OfferStatus.Applied },
    ],
    position: 'Cloud Engineer',
    slug: 'cloud-engineer',
    link: 'http://example.com/cloud',
    company: 'CloudTech',
    companyType: OfferCompanyType.Outsourcing,
    location: OfferLocation.Remote,
    status: OfferStatus.Applied,
    priority: OfferPriority.Medium,
    minSalary: 6000,
    maxSalary: 10250,
    salaryCurrency: OfferSalaryCurrency.EUR,
    email: 'careers@cloudtech.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 4), status: OfferStatus.Applied },
      { date: subtractDays(today, 2), status: OfferStatus.Interviewing },
    ],
    position: 'Security Specialist',
    slug: 'security-specialist',
    link: 'http://example.com/security',
    company: 'SecureTech',
    companyType: OfferCompanyType.Product,
    location: OfferLocation.OnSite,
    status: OfferStatus.Interviewing,
    priority: OfferPriority.High,
    minSalary: 6000,
    maxSalary: 9500,
    salaryCurrency: OfferSalaryCurrency.USD,
    email: 'jobs@securetech.com',
    description: defaultDescription,
  },
  {
    statusUpdates: [
      { date: subtractDays(today, 8), status: OfferStatus.Applied },
      { date: subtractDays(today, 3), status: OfferStatus.Interviewing },
      { date: subtractDays(today, 1), status: OfferStatus.Rejected },
    ],
    position: 'Game Developer',
    slug: 'game-developer',
    link: 'http://example.com/game-dev',
    company: 'GameWorks',
    companyType: OfferCompanyType.SoftwareHouse,
    location: OfferLocation.Hybrid,
    status: OfferStatus.Rejected,
    priority: OfferPriority.Low,
    minSalary: 3000,
    maxSalary: 6500,
    salaryCurrency: OfferSalaryCurrency.EUR,
    email: 'hr@gameworks.com',
    description: defaultDescription,
  },
];

export default defaultOffers;
