export enum OfferField {
  Position = 'position',
  Slug = 'slug',
  Link = 'link',
  Company = 'company',
  CompanyType = 'companyType',
  Location = 'location',
  Status = 'status',
  Priority = 'priority',
  MinSalary = 'minSalary',
  MaxSalary = 'maxSalary',
  SalaryCurrency = 'salaryCurrency',
  Email = 'email',
  Description = 'description',
}
